#include"sor3D.h"
#include<afx.h>
#include<math.h>
#include<iostream>
#define weight1 0
#define weight2 0
#define weight 0.8
using namespace std;
extern "C" void sor3D(int Xsize,int Ysize,int Zsize,int NoItr,int *BCScheme,double*x,double*y,double*z,double* p,double *pn,double *RHS,double eps)
{
	int i0=BCScheme[0];
	int ie=Xsize-BCScheme[1];
	int j0=BCScheme[2];
	int je=Ysize-BCScheme[3];
	int k0=BCScheme[4];
	int ke=Zsize-BCScheme[5];
	int iteration=0;
	float Error;
	float rms;
	float residue;
	while(iteration<NoItr)
	{

		Error=0;
		rms=0;
		residue=0;
		for(int k=k0;k<ke;k++)
		{
			for(int j=j0;j<je;j++)
			{
				for(int i=i0;i<ie;i++)
				{
					int index=i+j*Xsize+k*Xsize*Ysize;
					if(i==0&&j!=0&&j!=Ysize-1&&k!=0&&k!=Zsize-1)//left face;
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(5+weight1*8+weight2*4);
					}
					if(i==Xsize-1&&j!=0&&j!=Ysize-1&&k!=0&&k!=Zsize-1)//right face
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(5+weight1*8+weight2*4);
					}
					if(j==0&&i!=0&&i!=Xsize-1&&k!=0&&k!=Zsize-1)//top face
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(5+weight1*8+weight2*4);
					}
					if(j==Ysize-1&&i!=0&&i!=Xsize-1&&k!=0&&k!=Zsize-1)//bottom face
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(5+weight1*8+weight2*4);
					}
					if(k==0&&i!=0&&i!=Xsize-1&&j!=0&&j!=Ysize-1)//front face
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(5+weight1*8+weight2*4);
					}
					if(k==Zsize-1&&i!=0&&i!=Xsize-1&&j!=0&&j!=Ysize-1)//Back face
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(5+weight1*8+weight2*4);
					}
					if(i==0&&j==0&&k!=0&&k!=Zsize-1)//x=0 y=0 side
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(i==0&&j==Ysize-1&&k!=0&&k!=Zsize-1)
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(i==0&&k==0&&j!=0&&j!=Ysize-1)
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(i==0&&k==Zsize-1&&j!=0&&j!=Ysize-1)
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(i==Xsize-1&&j==0&&k!=0&&k!=Zsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(i==Xsize-1&&j==Ysize-1&&k!=0&&k!=Zsize-1)
					{
						int index=i+j*Xsize+k*Xsize*Ysize;
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(i==Xsize-1&&k==0&&j!=0&&j!=Ysize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(i==Xsize-1&&k==Zsize-1&&j!=0&&j!=Ysize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(j==0&&k==0&&i!=0&&i!=Xsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(j==0&&k==Zsize-1&&i!=0&&i!=Xsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(j==Ysize-1&&k==0&&i!=0&&i!=Xsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);
					}
					if(j==Ysize-1&&k==Zsize-1&&i!=0&&i!=Xsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(4+weight1*5+weight2*2);


					}
					if(i==0&&j==0&&k==0)
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i==0&&j==0&&k==Zsize-1)
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i==0&&j==Ysize-1&&k==0)
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i==0&&j==Ysize-1&&k==Zsize-1)
					{
						pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//	pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i==Xsize-1&&j==0&&k==0)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i==Xsize-1&&j==0&&k==Zsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i==Xsize-1&&j==Ysize-1&&k==0)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//	pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i==Xsize-1&&j==Ysize-1&&k==Zsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(3+weight1*3+weight2);
					}
					if(i!=0&&i!=Xsize-1&&j!=0&&j!=Ysize-1&&k!=0&&k!=Zsize-1)
					{
						pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
						pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						pn[index]+=RHS[index];
						pn[index]=pn[index]/(6+weight1*12+weight2*8);
					}
					pn[index]=p[index]+weight*(pn[index]-p[index]);
				}
			}
		}
		for(int k=1;k<Zsize-1;k++)
		{
			for(int j=1;j<Ysize-1;j++)
			{
				for(int i=1;i<Xsize-1;i++)
				{
					int index=i+j*Xsize+k*Xsize*Ysize;
					double temp;
					temp=pn[i-1+j*Xsize+k*Xsize*Ysize]+pn[i+1+j*Xsize+k*Xsize*Ysize]+pn[i+(j-1)*Xsize+k*Xsize*Ysize]+pn[i+(j+1)*Xsize+k*Xsize*Ysize]+pn[i+j*Xsize+(k-1)*Xsize*Ysize]+pn[i+j*Xsize+(k+1)*Xsize*Ysize];
					temp+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
					temp+=pn[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
					temp+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
					temp+=pn[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
					temp+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
					temp+=pn[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
					temp+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
					temp+=pn[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
					temp+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
					temp+=pn[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
					temp+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
					temp+=pn[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
					temp+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
					temp+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
					temp+=pn[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
					temp+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
					temp+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
					temp+=pn[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
					temp+=pn[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
					temp+=pn[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
					temp+=-(6+weight1*12+weight2*8)*pn[index];
					temp+=RHS[index];
					residue+=abs(temp);
					//Error+=(pn[index]-pBC[index])*(pn[index]-pBC[index]);
					rms+=(pn[index]-p[index])*(pn[index]-p[index]);
				}
			}	
		}
		residue=residue/Xsize/Ysize/Zsize;
		//Error=sqrt(Error/Xsize/Ysize/Zsize);
		rms=sqrt(rms/Xsize/Ysize/Zsize);
		cout<<"Iteration: "<<iteration<<" res: "<<residue<<" rms: "<<rms<<endl;
		if(residue<eps)
		{
			memcpy(p,pn,sizeof(double)*Xsize*Ysize*Zsize);
			return;
		}
		else
		{

			for(int i=i0;i<ie;i++)
			{
				for(int j=j0;j<je;j++)
				{
					for(int k=k0;k<ke;k++)
					{
						int index=i+j*Xsize+k*Xsize*Ysize;
						p[index]=pn[index];
						pn[index]=0;
					}
				}	
			}
			iteration++;
			//Error=0;
			rms=0;
			residue=0;
			for(int i=ie-1;i>=i0;i--)
			{
				for(int j=je-1;j>=j0;j--)
				{
					for(int k=ke-1;k>=k0;k--)
					{
						int index=i+j*Xsize+k*Xsize*Ysize;
						if(i==0&&j!=0&&j!=Ysize-1&&k!=0&&k!=Zsize-1)//left face;
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(5+weight1*8+weight2*4);
						}
						if(i==Xsize-1&&j!=0&&j!=Ysize-1&&k!=0&&k!=Zsize-1)//right face
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(5+weight1*8+weight2*4);
						}
						if(j==0&&i!=0&&i!=Xsize-1&&k!=0&&k!=Zsize-1)//top face
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(5+weight1*8+weight2*4);
						}
						if(j==Ysize-1&&i!=0&&i!=Xsize-1&&k!=0&&k!=Zsize-1)//bottom face
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(5+weight1*8+weight2*4);
						}
						if(k==0&&i!=0&&i!=Xsize-1&&j!=0&&j!=Ysize-1)//front face
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(5+weight1*8+weight2*4);
						}
						if(k==Zsize-1&&i!=0&&i!=Xsize-1&&j!=0&&j!=Ysize-1)//Back face
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(5+weight1*8+weight2*4);
						}
						if(i==0&&j==0&&k!=0&&k!=Zsize-1)//x=0 y=0 side
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(i==0&&j==Ysize-1&&k!=0&&k!=Zsize-1)
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(i==0&&k==0&&j!=0&&j!=Ysize-1)
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(i==0&&k==Zsize-1&&j!=0&&j!=Ysize-1)
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(i==Xsize-1&&j==0&&k!=0&&k!=Zsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(i==Xsize-1&&j==Ysize-1&&k!=0&&k!=Zsize-1)
						{
							int index=i+j*Xsize+k*Xsize*Ysize;
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(i==Xsize-1&&k==0&&j!=0&&j!=Ysize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(i==Xsize-1&&k==Zsize-1&&j!=0&&j!=Ysize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(j==0&&k==0&&i!=0&&i!=Xsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(j==0&&k==Zsize-1&&i!=0&&i!=Xsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(j==Ysize-1&&k==0&&i!=0&&i!=Xsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);
						}
						if(j==Ysize-1&&k==Zsize-1&&i!=0&&i!=Xsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(4+weight1*5+weight2*2);


						}
						if(i==0&&j==0&&k==0)
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i==0&&j==0&&k==Zsize-1)
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i==0&&j==Ysize-1&&k==0)
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i==0&&j==Ysize-1&&k==Zsize-1)
						{
							pn[index]=p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//	pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i==Xsize-1&&j==0&&k==0)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i==Xsize-1&&j==0&&k==Zsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							//pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i==Xsize-1&&j==Ysize-1&&k==0)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//	pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i==Xsize-1&&j==Ysize-1&&k==Zsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							//pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							//pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							//pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(3+weight1*3+weight2);
						}
						if(i!=0&&i!=Xsize-1&&j!=0&&j!=Ysize-1&&k!=0&&k!=Zsize-1)
						{
							pn[index]=p[i-1+j*Xsize+k*Xsize*Ysize]+p[i+1+j*Xsize+k*Xsize*Ysize]+p[i+(j-1)*Xsize+k*Xsize*Ysize]+p[i+(j+1)*Xsize+k*Xsize*Ysize]+p[i+j*Xsize+(k-1)*Xsize*Ysize]+p[i+j*Xsize+(k+1)*Xsize*Ysize];
							pn[index]+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
							pn[index]+=p[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
							pn[index]+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=p[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
							pn[index]+=RHS[index];
							pn[index]=pn[index]/(6+weight1*12+weight2*8);
						}
						pn[index]=p[index]+weight*(pn[index]-p[index]);
					}
				}
			}
			for(int k=1;k<Zsize-1;k++)
			{
				for(int j=1;j<Ysize-1;j++)
				{
					for(int i=1;i<Xsize-1;i++)
					{
						int index=i+j*Xsize+k*Xsize*Ysize;
						double temp;
						temp=pn[i-1+j*Xsize+k*Xsize*Ysize]+pn[i+1+j*Xsize+k*Xsize*Ysize]+pn[i+(j-1)*Xsize+k*Xsize*Ysize]+pn[i+(j+1)*Xsize+k*Xsize*Ysize]+pn[i+j*Xsize+(k-1)*Xsize*Ysize]+pn[i+j*Xsize+(k+1)*Xsize*Ysize];
						temp+=pn[i-1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						temp+=pn[i-1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						temp+=pn[i+1+(j-1)*Xsize+k*Xsize*Ysize]*weight1;
						temp+=pn[i+1+(j+1)*Xsize+k*Xsize*Ysize]*weight1;
						temp+=pn[i-1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						temp+=pn[i-1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						temp+=pn[i+1+j*Xsize+(k-1)*Xsize*Ysize]*weight1;
						temp+=pn[i+1+j*Xsize+(k+1)*Xsize*Ysize]*weight1;
						temp+=pn[i+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						temp+=pn[i+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						temp+=pn[i+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight1;
						temp+=pn[i+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight1;
						temp+=pn[i-1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						temp+=pn[i-1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						temp+=pn[i-1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						temp+=pn[i+1+(j-1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						temp+=pn[i+1+(j+1)*Xsize+(k-1)*Xsize*Ysize]*weight2;
						temp+=pn[i+1+(j-1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						temp+=pn[i-1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						temp+=pn[i+1+(j+1)*Xsize+(k+1)*Xsize*Ysize]*weight2;
						temp+=-(6+weight1*12+weight2*8)*pn[index];
						temp+=RHS[index];
						residue+=abs(temp);
						//Error+=(pn[index]-pBC[index])*(pn[index]-pBC[index]);
						rms+=(pn[index]-p[index])*(pn[index]-p[index]);
					}
				}	
			}
			residue=residue/Xsize/Ysize/Zsize;
			//Error=sqrt(Error/Xsize/Ysize/Zsize);
			rms=sqrt(rms/Xsize/Ysize/Zsize);
			if(residue<eps)
			{
				memcpy(p,pn,sizeof(double)*Xsize*Ysize*Zsize);
				return;
			}
			else
			{

				for(int i=i0;i<ie;i++)
				{
					for(int j=j0;j<je;j++)
					{
						for(int k=k0;k<ke;k++)
						{
							int index=i+j*Xsize+k*Xsize*Ysize;
							p[index]=pn[index];
							pn[index]=0;
						}
					}	
				}
				iteration++;
			}
		}

	}
}